### ISSUE TITLE
arch migrator thinks that this failed

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/make-feedstock#14]
https://conda-forge.org/status/
shows that this hasn't migrated

but the package appears on anaconda.org
https://anaconda.org/conda-forge/make

**Comment by scopatz** [comment]
Odd

**Comment by hmaarrfk** [comment]
can we simply retrigger it and upload a new build number?

**Comment by scopatz** [comment]
I think you need to add the `bot-rerun` label to the original PR

**Comment by hmaarrfk** [comment]
I don't have the permissions to do that so maybe @mariusvniekerk can?

**Comment by scopatz** [comment]
hmm the bot never opened a PR against this repo

**Comment by hmaarrfk** [comment]
what is this: https://github.com/conda-forge/make-feedstock/pull/13

**Comment by scopatz** [comment]
Oh yea

**Comment by jakirkham** [comment]
Is this still an issue?

**Comment by hmaarrfk** [comment]
I guess not
