### ISSUE TITLE
Make available older versions of make

### ISSUE THREAD

**Issue by phil-blain** [conda-forge/make-feedstock#15]
Issue: Only make 4.2.1 (latest) is available here (as well as in the `defaults` channel). I would like to test older versions, but I'm not sure how to add them to this repo. What should I do in the pull request ? Is there guidance for that somewhere?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/[redacted]/.conda/envs/make:
#
libgcc-ng                 9.1.0                hdf63c60_0  
make                      4.2.1                h1bed415_1 
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : /[redacted]/anaconda_5.0.1-[redacted]_ubuntu-14.04-amd64-64/x  (read only)
    default environment : /home/[redacted]/.conda/envs/make
       envs directories : /home/[redacted]/.conda/envs
                          /[redacted]/anaconda_5.0.1-[redacted]_ubuntu-14.04-amd64-64/x/envs
          package cache : /[redacted]/anaconda_5.0.1-[redacted]_ubuntu-14.04-amd64-64/x/pkgs
                          /home/[redacted]/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/[redacted]/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.14 Linux/3.10.0-514.el7.x86_64 debian/jessie/sid glibc/2.19    
                UID:GID : 67524:66086
```
</details>

**Comment by scopatz** [comment]
Hi there @phil-blain!  The docs on how to update (and downgrade) packages can be found at https://conda-forge.org/docs/maintainer/updating_pkgs.html

Basically, you'll need to put in a PR where you change the `recipe/meta.yaml` file to have the correct version number and tarball hash (usually sha256) and reduce the build number to `0`.  Normally, that's it assuming dependencies didn't differ, etc.  The CI systems here will try to build the package, so we'll know whether it works or not before we merge.

**Comment by asmeurer** [comment]
That document doesn't specify how to get an older version built (unless I missed it). What's the correct way to do that. Create a new branch for the old version? Or just push a commit to master with the old version and revert it after it is built?

**Comment by scopatz** [comment]
You don't need to do anything other than change the version.  You don't need to revert afterward. The feedstock doesn't need to be in lock-step with the most recent version.  Basically one version change is the same as any other, it is just that the 99.9% use case is to update versions

**Comment by phil-blain** [comment]
I'll close this issue as I don't need older versions of make anymore for my projects. If the need comes I know how to add them!
